### ISSUE TITLE
Launcher is unable to load profiles

### ISSUE THREAD

**Issue by lferro9000** [Team-RAM/RAM#46]
Running the Java minecraft version as intalled in by twitch.tv app, with a bit extra memory due to wanting to run a local single player server in this maching.

# OS
```
macOS Catalina 10.15.4
```

# Java
```
java -version 
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

# launcher_profiles.json 
```
{
  "profiles": {
    "RAM - Really Awesome Mods": {
      "name": "RAM - Really Awesome Mods",
      "gameDir": "/Users/luis/Twitch/Minecraft/Instances/RAM - Really Awesome Mods",
      "lastVersionId": "forge-31.1.36",
      "javaArgs": "-Xmx5632m -Xms256m -XX:PermSize\u003d256m -Dfml.ignorePatchDiscrepancies\u003dtrue -Dfml.ignoreInvalidMinecraftCertificates\u003dtrue -Duser.language\u003den -Duser.country\u003dUS",
      "resolution": {
        "width": 1024,
        "height": 768
      },
      "launcherVisibilityOnGameClose": "close launcher when game starts"
    }
  },
  "selectedProfile": "RAM - Really Awesome Mods",
  "clientToken": "0c571267-b13c-4e8a-ac11-a894f9677277",
  "authenticationDatabase": {
    "4331835a2fd44a78afe99562971dff6c": {
      "displayName": "Bladmeister",
      "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNjRlY2Q4ZDdkYWVjYTkyNDMxNTViOWRmOTg2ZDYwNyIsInlnZ3QiOiIxYzE0NzIxMDQ2NWE0ZGU4ODI1Y2MzMDlhMDg5Y2QxNyIsInNwciI6IjQzMzE4MzVhMmZkNDRhNzhhZmU5OTU2Mjk3MWRmZjZjIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODcwMjg1NjUsImlhdCI6MTU4Njg1NTc2NX0.xIjeRZsX9SHX62E7eWrEPcxGpnebRUzFQe_h48A0ZUo",
      "userid": "164ecd8d7daeca9243155b9df986d607",
      "uuid": "4331835a-2fd4-4a78-afe9-9562971dff6c",
      "username": "lferro9000@gmail.com"
    }
  },
  "selectedUser": "4331835a2fd44a78afe99562971dff6c",
  "launcherVersion": {
    "name": "1.6.91",
    "format": 21,
    "profilesFormat": 1
  }
}
```
# Log file
```
[10:44:08 INFO]: Minecraft Launcher 1.6.91 (through bootstrap 100) started on osx...
[10:44:08 INFO]: Current time is Apr 14, 2020 10:44:08 AM
[10:44:08 INFO]: System.getProperty('os.name') == 'Mac OS X'
[10:44:08 INFO]: System.getProperty('os.version') == '10.15.4'
[10:44:08 INFO]: System.getProperty('os.arch') == 'x86_64'
[10:44:08 INFO]: System.getProperty('java.version') == '1.8.0_241'
[10:44:08 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[10:44:08 INFO]: System.getProperty('sun.arch.data.model') == '64'
[10:44:08 INFO]: proxy == DIRECT
[10:44:08 INFO]: JFX is already initialized
[10:44:09 INFO]: Refreshing local version list...
[10:44:09 INFO]: Refreshing remote version list...
[10:44:10 INFO]: Refresh complete.
[10:44:10 ERROR]: Unexpected exception refreshing profile list
com.google.gson.JsonSyntaxException: duplicate key: null
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.RemoteVersionList.getCompleteVersion(RemoteVersionList.java:32) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:213) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.CompleteMinecraftVersion.resolve(CompleteMinecraftVersion.java:268) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.CompleteMinecraftVersion.resolve(CompleteMinecraftVersion.java:255) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getVersionSyncInfo(MinecraftVersionManager.java:171) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getVersions(MinecraftVersionManager.java:105) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.game.GameLaunchDispatcher.getStatus(GameLaunchDispatcher.java:35) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.ui.bottombar.PlayButtonPanel.checkState(PlayButtonPanel.java:94) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.ui.bottombar.PlayButtonPanel.onProfilesRefreshed(PlayButtonPanel.java:90) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.profile.ProfileManager.fireRefreshEvent(ProfileManager.java:100) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.profile.ProfileManager.loadProfiles(ProfileManager.java:88) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:183) [launcher.jar:1.6.91]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[10:44:10 INFO]: Refreshing auth...
[10:44:10 INFO]: Logging in with access token
[10:44:10 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
com.google.gson.JsonSyntaxException: duplicate key: null
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.RemoteVersionList.getCompleteVersion(RemoteVersionList.java:32) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:213) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.CompleteMinecraftVersion.resolve(CompleteMinecraftVersion.java:268) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.CompleteMinecraftVersion.resolve(CompleteMinecraftVersion.java:255) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getVersionSyncInfo(MinecraftVersionManager.java:171) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getVersions(MinecraftVersionManager.java:105) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.ui.bottombar.PlayerInfoPanel.checkState(PlayerInfoPanel.java:96) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.ui.bottombar.PlayerInfoPanel$2.run(PlayerInfoPanel.java:78) ~[launcher.jar:1.6.91]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_241]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_241]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_241]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_241]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_241]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_241]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_241]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_241]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_241]
[10:44:11 ERROR]: Unhandled exception in executor com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask@7d784ae8
java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: duplicate key: null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_241]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_241]
	at com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask.done(ExceptionalThreadPoolExecutor.java:58) [launcher.jar:1.6.91]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384) [?:1.8.0_241]
	at java.util.concurrent.FutureTask.setException(FutureTask.java:251) [?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(FutureTask.java:271) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: com.google.gson.JsonSyntaxException: duplicate key: null
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.RemoteVersionList.getCompleteVersion(RemoteVersionList.java:32) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:213) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.CompleteMinecraftVersion.resolve(CompleteMinecraftVersion.java:268) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.CompleteMinecraftVersion.resolve(CompleteMinecraftVersion.java:255) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getVersionSyncInfo(MinecraftVersionManager.java:171) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getVersions(MinecraftVersionManager.java:105) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.game.GameLaunchDispatcher.getStatus(GameLaunchDispatcher.java:35) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.ui.bottombar.PlayButtonPanel.checkState(PlayButtonPanel.java:94) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.ui.bottombar.PlayButtonPanel.onProfilesRefreshed(PlayButtonPanel.java:90) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.profile.ProfileManager.fireRefreshEvent(ProfileManager.java:100) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.Launcher.ensureLoggedIn(Launcher.java:265) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:213) ~[launcher.jar:1.6.91]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_241]
	... 3 more
[10:44:11 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
com.google.gson.JsonSyntaxException: duplicate key: null
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.RemoteVersionList.getCompleteVersion(RemoteVersionList.java:32) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:213) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.CompleteMinecraftVersion.resolve(CompleteMinecraftVersion.java:268) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.CompleteMinecraftVersion.resolve(CompleteMinecraftVersion.java:255) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getVersionSyncInfo(MinecraftVersionManager.java:171) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getVersions(MinecraftVersionManager.java:105) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.ui.bottombar.PlayerInfoPanel.checkState(PlayerInfoPanel.java:96) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.ui.bottombar.PlayerInfoPanel$2.run(PlayerInfoPanel.java:78) ~[launcher.jar:1.6.91]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_241]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_241]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_241]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_241]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_241]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_241]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_241]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_241]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_241]
```

**Comment by Darkere** [comment]
My recommendation is to ditch Twitch and use something else like MultiMc, GDlauncher or AT launcher.

If you want to fix the issue instead you can find solutions here: 
https://bugs.mojang.com/browse/MCL-11993

The file to replace should be somewhere under `/twitch/install`

**Comment by lferro9000** [comment]
Will sort it :)
